spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tcpsession
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.auto: create-drop

logging:
  level:
    org:
      hibernate.sql: debug